{
  "hash": "688edfc19b13f2f34b9e50339dbaa793",
  "result": {
    "markdown": "---\ntitle: \"Overlapping genes\"\nauthor: Gibran Hemani\ndate: \"2023-02-18\"\ncategories: [genomics]\n---\n\n\n## Background\n\nFor a list of positions, identify all genes that overlap +/- 200kb.\n\nUse Ensembl database of gene positions \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(EnsDb.Hsapiens.v75) # For convenience hg19\nlibrary(ieugwasr)\nlibrary(dplyr)\ngenelist <- genes(EnsDb.Hsapiens.v75) %>%\n    subset(gene_biotype==\"protein_coding\")\ngenelist\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGRanges object with 22810 ranges and 6 metadata columns:\n                  seqnames            ranges strand |         gene_id\n                     <Rle>         <IRanges>  <Rle> |     <character>\n  ENSG00000186092        1       69091-70008      + | ENSG00000186092\n  ENSG00000237683        1     134901-139379      - | ENSG00000237683\n  ENSG00000235249        1     367640-368634      + | ENSG00000235249\n  ENSG00000185097        1     621059-622053      - | ENSG00000185097\n  ENSG00000269831        1     738532-739137      - | ENSG00000269831\n              ...      ...               ...    ... .             ...\n  ENSG00000187191        Y 26909216-26959626      - | ENSG00000187191\n  ENSG00000205916        Y 26980008-27053183      + | ENSG00000205916\n  ENSG00000185894        Y 27177048-27208695      - | ENSG00000185894\n  ENSG00000172288        Y 27768264-27771049      + | ENSG00000172288\n  ENSG00000269393        Y 28111776-28114889      - | ENSG00000269393\n                    gene_name   gene_biotype seq_coord_system      symbol\n                  <character>    <character>      <character> <character>\n  ENSG00000186092       OR4F5 protein_coding       chromosome       OR4F5\n  ENSG00000237683  AL627309.1 protein_coding       chromosome  AL627309.1\n  ENSG00000235249      OR4F29 protein_coding       chromosome      OR4F29\n  ENSG00000185097      OR4F16 protein_coding       chromosome      OR4F16\n  ENSG00000269831  AL669831.1 protein_coding       chromosome  AL669831.1\n              ...         ...            ...              ...         ...\n  ENSG00000187191        DAZ3 protein_coding       chromosome        DAZ3\n  ENSG00000205916        DAZ4 protein_coding       chromosome        DAZ4\n  ENSG00000185894       BPY2C protein_coding       chromosome       BPY2C\n  ENSG00000172288        CDY1 protein_coding       chromosome        CDY1\n  ENSG00000269393  AC007965.1 protein_coding       chromosome  AC007965.1\n                                    entrezid\n                                      <list>\n  ENSG00000186092                      79501\n  ENSG00000237683 101929819,100996768,728728\n  ENSG00000235249         729759,81399,26683\n  ENSG00000185097         729759,81399,26683\n  ENSG00000269831                       <NA>\n              ...                        ...\n  ENSG00000187191                57055,57054\n  ENSG00000205916           57135,57055,1617\n  ENSG00000185894         442868,442867,9083\n  ENSG00000172288                253175,9085\n  ENSG00000269393                       <NA>\n  -------\n  seqinfo: 273 sequences (1 circular) from GRCh37 genome\n```\n:::\n:::\n\n\nSNP list\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnps_cluster1 <- c(\"rs1097327\",\"rs2186120\",\"rs2166172\",\"rs75641275\",\"rs12037698\",\"rs1446585\",\"rs16846140\",\"rs13062093\",\"rs2051559\",\"rs6861649\",\"rs2281819\",\"rs12662900\",\"rs9388681\",\"rs17132130\",\"rs215634\",\"rs79682948\",\"rs2192649\",\"rs13294945\",\"rs7357754\",\"rs4749937\",\"rs1465900\",\"rs1799992\",\"rs55938344\",\"rs7987928\",\"rs7331420\",\"rs9522279\",\"rs55689274\",\"rs4777541\",\"rs7189149\",\"rs11079849\",\"rs113230003\",\"rs150998792\")\n```\n:::\n\n\nGet positions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi <- associations(snps_cluster1, \"ukb-a-248\")\ntarget <- GRanges(bmi$chr, IRanges(bmi$position - 200000, bmi$position + 200000))\ntarget\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGRanges object with 30 ranges and 0 metadata columns:\n       seqnames              ranges strand\n          <Rle>           <IRanges>  <Rle>\n   [1]        1   23137075-23537075      *\n   [2]        1   66253163-66653163      *\n   [3]        1   91008514-91408514      *\n   [4]        1   98127133-98527133      *\n   [5]        1 243384345-243784345      *\n   ...      ...                 ...    ...\n  [26]       15   47558909-47958909      *\n  [27]       15   72882240-73282240      *\n  [28]       16   68944151-69344151      *\n  [29]       17   46890785-47290785      *\n  [30]       19   18260956-18660956      *\n  -------\n  seqinfo: 16 sequences from an unspecified genome; no seqlengths\n```\n:::\n:::\n\n\nFind overlaps with genelist\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlaps <- findOverlaps(target, genelist)\noverlaps\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHits object with 116 hits and 0 metadata columns:\n        queryHits subjectHits\n        <integer>   <integer>\n    [1]         1         306\n    [2]         1         307\n    [3]         1         308\n    [4]         1         309\n    [5]         1         310\n    ...       ...         ...\n  [112]        30        9758\n  [113]        30        9759\n  [114]        30        9760\n  [115]        30        9761\n  [116]        30        9762\n  -------\n  queryLength: 30 / subjectLength: 22810\n```\n:::\n:::\n\n\nOverall about 116 overlapping protein coding genes found for 30 SNPs.\n\n---\n\nTry with all ensembl annotations, not just protein coding\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenelist_all <- genes(EnsDb.Hsapiens.v75)\ngenelist_all\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGRanges object with 64102 ranges and 6 metadata columns:\n                  seqnames            ranges strand |         gene_id\n                     <Rle>         <IRanges>  <Rle> |     <character>\n  ENSG00000223972        1       11869-14412      + | ENSG00000223972\n  ENSG00000227232        1       14363-29806      - | ENSG00000227232\n  ENSG00000243485        1       29554-31109      + | ENSG00000243485\n  ENSG00000237613        1       34554-36081      - | ENSG00000237613\n  ENSG00000268020        1       52473-54936      + | ENSG00000268020\n              ...      ...               ...    ... .             ...\n  ENSG00000224240        Y 28695572-28695890      + | ENSG00000224240\n  ENSG00000227629        Y 28732789-28737748      - | ENSG00000227629\n  ENSG00000237917        Y 28740998-28780799      - | ENSG00000237917\n  ENSG00000231514        Y 28772667-28773306      - | ENSG00000231514\n  ENSG00000235857        Y 59001391-59001635      + | ENSG00000235857\n                    gene_name gene_biotype seq_coord_system      symbol\n                  <character>  <character>      <character> <character>\n  ENSG00000223972     DDX11L1   pseudogene       chromosome     DDX11L1\n  ENSG00000227232      WASH7P   pseudogene       chromosome      WASH7P\n  ENSG00000243485  MIR1302-10      lincRNA       chromosome  MIR1302-10\n  ENSG00000237613     FAM138A      lincRNA       chromosome     FAM138A\n  ENSG00000268020      OR4G4P   pseudogene       chromosome      OR4G4P\n              ...         ...          ...              ...         ...\n  ENSG00000224240     CYCSP49   pseudogene       chromosome     CYCSP49\n  ENSG00000227629  SLC25A15P1   pseudogene       chromosome  SLC25A15P1\n  ENSG00000237917     PARP4P1   pseudogene       chromosome     PARP4P1\n  ENSG00000231514     FAM58CP   pseudogene       chromosome     FAM58CP\n  ENSG00000235857     CTBP2P1   pseudogene       chromosome     CTBP2P1\n                                           entrezid\n                                             <list>\n  ENSG00000223972               100287596,100287102\n  ENSG00000227232                  100287171,653635\n  ENSG00000243485 100422919,100422834,100422831,...\n  ENSG00000237613              654835,645520,641702\n  ENSG00000268020                              <NA>\n              ...                               ...\n  ENSG00000224240                              <NA>\n  ENSG00000227629                              <NA>\n  ENSG00000237917                              <NA>\n  ENSG00000231514                              <NA>\n  ENSG00000235857                              <NA>\n  -------\n  seqinfo: 273 sequences (1 circular) from GRCh37 genome\n```\n:::\n\n```{.r .cell-code}\noverlaps1 <- findOverlaps(target, genelist_all)\noverlaps1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHits object with 277 hits and 0 metadata columns:\n        queryHits subjectHits\n        <integer>   <integer>\n    [1]         1         725\n    [2]         1         728\n    [3]         1         729\n    [4]         1         730\n    [5]         1         731\n    ...       ...         ...\n  [273]        30       26788\n  [274]        30       26789\n  [275]        30       26790\n  [276]        30       26791\n  [277]        30       26792\n  -------\n  queryLength: 30 / subjectLength: 64102\n```\n:::\n:::\n\n\nStill only 277\n\n---\n\nTry with HumanHT-12 v3.0 probes. Download manifest file to get probe coordinates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- tempfile()\ndownload.file(\"https://emea.support.illumina.com/content/dam/illumina-support/documents/downloads/productfiles/humanht-12/v3/humanht-12_v3_0_r3_11283641_a_txt.zip\", temp)\nlibrary(data.table)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'data.table'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:dplyr':\n\n    between, first, last\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:GenomicRanges':\n\n    shift\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:IRanges':\n\n    shift\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:S4Vectors':\n\n    first, second\n```\n:::\n\n```{.r .cell-code}\na <- fread(paste0(\"unzip -p \", temp), skip=8)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nTaking input= as a system command ('unzip -p /var/folders/pp/6w3v08jx2p3ct76tptkmt0qh0000gq/T//RtmpYrlwQo/file7e866d3df1ff') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in fread(paste0(\"unzip -p \", temp), skip = 8): Stopped early on line\n48813. Expected 28 fields but found 1. Consider fill=TRUE and comment.char=.\nFirst discarded non-empty line: <<[Controls]>>\n```\n:::\n\n```{.r .cell-code}\nstr(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nClasses 'data.table' and 'data.frame':\t48803 obs. of  28 variables:\n $ Species              : chr  \"Homo sapiens\" \"Homo sapiens\" \"Homo sapiens\" \"Homo sapiens\" ...\n $ Source               : chr  \"RefSeq\" \"Unigene\" \"RefSeq\" \"RefSeq\" ...\n $ Search_Key           : chr  \"ILMN_44919\" \"ILMN_127219\" \"ILMN_139282\" \"ILMN_5006\" ...\n $ Transcript           : chr  \"ILMN_44919\" \"ILMN_127219\" \"ILMN_139282\" \"ILMN_5006\" ...\n $ ILMN_Gene            : chr  \"LOC23117\" \"HS.575038\" \"FCGR2B\" \"TRIM44\" ...\n $ Source_Reference_ID  : chr  \"XM_933824.1\" \"Hs.575038\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ RefSeq_ID            : chr  \"XM_933824.1\" \"\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ Unigene_ID           : chr  \"\" \"Hs.575038\" \"\" \"\" ...\n $ Entrez_Gene_ID       : int  23117 NA 2213 54765 653895 158833 387701 NA 56905 NA ...\n $ GI                   : int  89040007 10437021 88952550 29029528 89033487 61888901 89031576 27826545 153251858 1999235 ...\n $ Accession            : chr  \"XM_933824.1\" \"AK024680\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ Symbol               : chr  \"LOC23117\" \"\" \"FCGR2B\" \"TRIM44\" ...\n $ Protein_Product      : chr  \"XP_938917.1\" \"\" \"XP_943944.1\" \"NP_060053.2\" ...\n $ Probe_Id             : chr  \"ILMN_1725881\" \"ILMN_1910180\" \"ILMN_1804174\" \"ILMN_1796063\" ...\n $ Array_Address_Id     : int  1710221 5900364 2480717 1300239 4480719 6020725 3870215 2710020 870110 290020 ...\n $ Probe_Type           : chr  \"I\" \"S\" \"I\" \"S\" ...\n $ Probe_Start          : int  122 1409 1643 2901 25 782 301 324 3585 139 ...\n $ Probe_Sequence       : chr  \"GGCTCCTCTTTGGGCTCCTACTGGAATTTATCAGCCATCAGTGCATCTCT\" \"ACACCTTCAGGAGGGAAGCCCTTATTTCTGGGTTGAACTCCCCTTCCATG\" \"TAGGGGCAATAGGCTATACGCTACAGCCTAGGTGTGTAGTAGGCCACACC\" \"CCTGCCTGTCTGCCTGTGACCTGTGTACGTATTACAGGCTTTAGGACCAG\" ...\n $ Chromosome           : chr  \"16\" \"2\" \"\" \"11\" ...\n $ Probe_Chr_Orientation: chr  \"-\" \"+\" \"\" \"+\" ...\n $ Probe_Coordinates    : chr  \"21766363-21766363:21769901-21769949\" \"206352194-206352243\" \"\" \"35786070-35786119\" ...\n $ Cytoband             : chr  \"16p12.2a\" \"\" \"1q23.3b\" \"11p13a\" ...\n $ Definition           : chr  \"PREDICTED: Homo sapiens KIAA0220-like protein, transcript variant 11 (LOC23117), mRNA.\" \"Homo sapiens cDNA: FLJ21027 fis, clone CAE07110\" \"PREDICTED: Homo sapiens Fc fragment of IgG, low affinity IIb, receptor (CD32) (FCGR2B), mRNA.\" \"Homo sapiens tripartite motif-containing 44 (TRIM44), mRNA.\" ...\n $ Ontology_Component   : chr  \"\" \"\" \"The membrane surrounding a cell that separates the cell from its external environment. It consists of a phospho\"| __truncated__ \"\" ...\n $ Ontology_Process     : chr  \"\" \"\" \"Any immune system process that functions in the calibrated response of an organism to a potential internal or i\"| __truncated__ \"\" ...\n $ Ontology_Function    : chr  \"\" \"\" \"Combining with an extracellular or intracellular messenger to initiate a change in cell activity [goid 4872] [e\"| __truncated__ \"\" ...\n $ Synonyms             : chr  \"\" \"\" \"\" \"MGC3490; MC7; HSA249128; DIPB\" ...\n $ Obsolete_Probe_Id    : chr  \"\" \"\" \"\" \"MGC3490; MC7; HSA249128; DIPB\" ...\n - attr(*, \".internal.selfref\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\na$bp <- sapply(strsplit(a$Probe_Coordinates, \"-\"), function(o) as.numeric(o[1]))\nstr(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nClasses 'data.table' and 'data.frame':\t48803 obs. of  29 variables:\n $ Species              : chr  \"Homo sapiens\" \"Homo sapiens\" \"Homo sapiens\" \"Homo sapiens\" ...\n $ Source               : chr  \"RefSeq\" \"Unigene\" \"RefSeq\" \"RefSeq\" ...\n $ Search_Key           : chr  \"ILMN_44919\" \"ILMN_127219\" \"ILMN_139282\" \"ILMN_5006\" ...\n $ Transcript           : chr  \"ILMN_44919\" \"ILMN_127219\" \"ILMN_139282\" \"ILMN_5006\" ...\n $ ILMN_Gene            : chr  \"LOC23117\" \"HS.575038\" \"FCGR2B\" \"TRIM44\" ...\n $ Source_Reference_ID  : chr  \"XM_933824.1\" \"Hs.575038\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ RefSeq_ID            : chr  \"XM_933824.1\" \"\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ Unigene_ID           : chr  \"\" \"Hs.575038\" \"\" \"\" ...\n $ Entrez_Gene_ID       : int  23117 NA 2213 54765 653895 158833 387701 NA 56905 NA ...\n $ GI                   : int  89040007 10437021 88952550 29029528 89033487 61888901 89031576 27826545 153251858 1999235 ...\n $ Accession            : chr  \"XM_933824.1\" \"AK024680\" \"XM_938851.1\" \"NM_017583.3\" ...\n $ Symbol               : chr  \"LOC23117\" \"\" \"FCGR2B\" \"TRIM44\" ...\n $ Protein_Product      : chr  \"XP_938917.1\" \"\" \"XP_943944.1\" \"NP_060053.2\" ...\n $ Probe_Id             : chr  \"ILMN_1725881\" \"ILMN_1910180\" \"ILMN_1804174\" \"ILMN_1796063\" ...\n $ Array_Address_Id     : int  1710221 5900364 2480717 1300239 4480719 6020725 3870215 2710020 870110 290020 ...\n $ Probe_Type           : chr  \"I\" \"S\" \"I\" \"S\" ...\n $ Probe_Start          : int  122 1409 1643 2901 25 782 301 324 3585 139 ...\n $ Probe_Sequence       : chr  \"GGCTCCTCTTTGGGCTCCTACTGGAATTTATCAGCCATCAGTGCATCTCT\" \"ACACCTTCAGGAGGGAAGCCCTTATTTCTGGGTTGAACTCCCCTTCCATG\" \"TAGGGGCAATAGGCTATACGCTACAGCCTAGGTGTGTAGTAGGCCACACC\" \"CCTGCCTGTCTGCCTGTGACCTGTGTACGTATTACAGGCTTTAGGACCAG\" ...\n $ Chromosome           : chr  \"16\" \"2\" \"\" \"11\" ...\n $ Probe_Chr_Orientation: chr  \"-\" \"+\" \"\" \"+\" ...\n $ Probe_Coordinates    : chr  \"21766363-21766363:21769901-21769949\" \"206352194-206352243\" \"\" \"35786070-35786119\" ...\n $ Cytoband             : chr  \"16p12.2a\" \"\" \"1q23.3b\" \"11p13a\" ...\n $ Definition           : chr  \"PREDICTED: Homo sapiens KIAA0220-like protein, transcript variant 11 (LOC23117), mRNA.\" \"Homo sapiens cDNA: FLJ21027 fis, clone CAE07110\" \"PREDICTED: Homo sapiens Fc fragment of IgG, low affinity IIb, receptor (CD32) (FCGR2B), mRNA.\" \"Homo sapiens tripartite motif-containing 44 (TRIM44), mRNA.\" ...\n $ Ontology_Component   : chr  \"\" \"\" \"The membrane surrounding a cell that separates the cell from its external environment. It consists of a phospho\"| __truncated__ \"\" ...\n $ Ontology_Process     : chr  \"\" \"\" \"Any immune system process that functions in the calibrated response of an organism to a potential internal or i\"| __truncated__ \"\" ...\n $ Ontology_Function    : chr  \"\" \"\" \"Combining with an extracellular or intracellular messenger to initiate a change in cell activity [goid 4872] [e\"| __truncated__ \"\" ...\n $ Synonyms             : chr  \"\" \"\" \"\" \"MGC3490; MC7; HSA249128; DIPB\" ...\n $ Obsolete_Probe_Id    : chr  \"\" \"\" \"\" \"MGC3490; MC7; HSA249128; DIPB\" ...\n $ bp                   : num  2.18e+07 2.06e+08 NA 3.58e+07 NA ...\n - attr(*, \".internal.selfref\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\na <- subset(a, !is.na(bp))\ndim(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42945    29\n```\n:::\n\n```{.r .cell-code}\nb <- GRanges(a$Chromosome, IRanges(a$bp, a$bp), Transcript=a$Transcript)\noverlaps2 <- findOverlaps(target, b)\noverlaps2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHits object with 165 hits and 0 metadata columns:\n        queryHits subjectHits\n        <integer>   <integer>\n    [1]         1        3073\n    [2]         1        3658\n    [3]         1       20306\n    [4]         1       25574\n    [5]         1       42634\n    ...       ...         ...\n  [161]        30       34706\n  [162]        30       36225\n  [163]        30       39738\n  [164]        30       39832\n  [165]        30       42330\n  -------\n  queryLength: 30 / subjectLength: 42945\n```\n:::\n:::\n\n\nStill only 165\n\n---\n\nLooks like the overlaps are actually only for eQTL SNP positions, rather than probe or annotation locations. So get MuTHER eQTL results, and lookup how many eQTLs overlap BMI SNPs +/-200kb\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- tempfile()\ndownload.file(\"http://www.muther.ac.uk/DataForWebsite/MuTHER_top_cis_eQTL_per_probe_Fat.txt.gz\", temp)\nb <- fread(paste0(\"gunzip -c \", temp))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nTaking input= as a system command ('gunzip -c /var/folders/pp/6w3v08jx2p3ct76tptkmt0qh0000gq/T//RtmpYrlwQo/file7e8627edacbb') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.\n```\n:::\n\n```{.r .cell-code}\nb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       CHR        PROBE   Gene       TSS       TSE        SNP SNP_INFO\n    1:   1 ILMN_1651229  IPO13  44185064  44206280   rs621559    0.997\n    2:  16 ILMN_1651230 TESSP1   2788487   2795134  rs6600200    0.939\n    3:   4 ILMN_1651235  AFAP1   7811339   7992553 rs13122226    0.853\n    4:  16 ILMN_1651237   CDT1  87397686  87403167  rs7500824    0.924\n    5:  17 ILMN_1651238  TRPV1   3415489   3445874 rs11078512    1.000\n   ---                                                                \n23223:  16 ILMN_2415776   WWOX  76691051  76691596  rs4887991    0.918\n23224:   3 ILMN_2415786   CD96 112743615 112853896  rs2634545    0.968\n23225:  17 ILMN_2415826  CYTSB  19999993  20081083  rs9911605    0.907\n23226:  23 ILMN_2415911  ENOX2 129585037 129864889  rs5932853    1.000\n23227:   9 ILMN_2415949   MRRF 124066702 124125561 rs12156510    0.851\n        SNP_Coor A1 Freq_A1   Fat_beta Fat_sebeta     Fat_p     LCL_beta\n    1:  43417998  G  0.9370  0.0779514 0.02857380 0.0064000  0.017058900\n    2:   2383771  T  0.3520 -0.0145240 0.00513359 0.0047000  0.004936040\n    3:   8171020  T  0.7380  0.0182723 0.00577418 0.0016000 -0.007693140\n    4:  86856992  G  0.6750  0.0203629 0.00648465 0.0017000  0.046034300\n    5:   4345191  G  0.8340 -0.0239871 0.00733934 0.0011000 -0.000181549\n   ---                                                                  \n23223:  77478564  G  0.3230  0.0650150 0.01937710 0.0007929  0.001083580\n23224: 112459042  T  0.6060  0.0459368 0.01336570 0.0005884 -0.051241700\n23225:  19957683  T  0.1950  0.0240481 0.00645100 0.0001932 -0.003798860\n23226: 130113107  T  0.2265 -0.0298614 0.01057420 0.0047000 -0.024893400\n23227: 123959794  G  0.2710  0.0456188 0.01213610 0.0001706  0.006575610\n       LCL_sebeta  LCL_p    Skin_beta Skin_sebeta Skin_p\n    1: 0.02432060 0.4830 -0.010652100  0.02916640 0.7149\n    2: 0.00545402 0.3655 -0.005986190  0.00569460 0.2932\n    3: 0.00617687 0.2130  0.003836190  0.00581005 0.5091\n    4: 0.02385430 0.0536 -0.021171000  0.01904700 0.2663\n    5: 0.00746635 0.9806 -0.000843489  0.00764613 0.9122\n   ---                                                  \n23223: 0.01777060 0.9514 -0.003480850  0.02788380 0.9007\n23224: 0.03088650 0.0971 -0.015326200  0.01731080 0.3760\n23225: 0.00897785 0.6722  0.001083930  0.00802034 0.8925\n23226: 0.01307960 0.0570  0.001724490  0.01235640 0.8890\n23227: 0.01614070 0.6837  0.014399600  0.01556960 0.3550\n```\n:::\n\n```{.r .cell-code}\nbg <- GRanges(b$CHR, IRanges(b$SNP_Coor, b$SNP_Coor), Gene=b$Gene)\nbg\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGRanges object with 23227 ranges and 1 metadata column:\n          seqnames    ranges strand |        Gene\n             <Rle> <IRanges>  <Rle> | <character>\n      [1]        1  43417998      * |       IPO13\n      [2]       16   2383771      * |      TESSP1\n      [3]        4   8171020      * |       AFAP1\n      [4]       16  86856992      * |        CDT1\n      [5]       17   4345191      * |       TRPV1\n      ...      ...       ...    ... .         ...\n  [23223]       16  77478564      * |        WWOX\n  [23224]        3 112459042      * |        CD96\n  [23225]       17  19957683      * |       CYTSB\n  [23226]       23 130113107      * |       ENOX2\n  [23227]        9 123959794      * |        MRRF\n  -------\n  seqinfo: 23 sequences from an unspecified genome; no seqlengths\n```\n:::\n\n```{.r .cell-code}\noverlaps3 <- findOverlaps(target, bg)\nlength(unique(b$Gene[overlaps3@to]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 106\n```\n:::\n:::\n\n\nStill not much. But I think in the script it suggests that all cis-SNPs were included without filtering for p-value, so actually it's looking for any overlap with any genes +/- 1Mb?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg <- GRanges(b$CHR, IRanges(b$TSS-1000000, b$TSS+1000000), Gene=b$Gene)\nbg\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGRanges object with 23227 ranges and 1 metadata column:\n          seqnames              ranges strand |        Gene\n             <Rle>           <IRanges>  <Rle> | <character>\n      [1]        1   43185064-45185064      * |       IPO13\n      [2]       16     1788487-3788487      * |      TESSP1\n      [3]        4     6811339-8811339      * |       AFAP1\n      [4]       16   86397686-88397686      * |        CDT1\n      [5]       17     2415489-4415489      * |       TRPV1\n      ...      ...                 ...    ... .         ...\n  [23223]       16   75691051-77691051      * |        WWOX\n  [23224]        3 111743615-113743615      * |        CD96\n  [23225]       17   18999993-20999993      * |       CYTSB\n  [23226]       23 128585037-130585037      * |       ENOX2\n  [23227]        9 123066702-125066702      * |        MRRF\n  -------\n  seqinfo: 23 sequences from an unspecified genome; no seqlengths\n```\n:::\n\n```{.r .cell-code}\noverlaps3 <- findOverlaps(target, bg)\nlength(unique(b$Gene[overlaps3@to]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 504\n```\n:::\n:::\n\n\nNow it's quite a it higher.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.2.1 Patched (2022-09-06 r82817)\nPlatform: aarch64-apple-darwin20 (64-bit)\nRunning under: macOS Monterey 12.6.2\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib\nLAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\nattached base packages:\n[1] stats4    stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] data.table_1.14.2         dplyr_1.0.10             \n [3] ieugwasr_0.1.5            EnsDb.Hsapiens.v75_2.99.0\n [5] ensembldb_2.22.0          AnnotationFilter_1.22.0  \n [7] GenomicFeatures_1.50.4    AnnotationDbi_1.60.0     \n [9] Biobase_2.56.0            GenomicRanges_1.50.2     \n[11] GenomeInfoDb_1.34.9       IRanges_2.32.0           \n[13] S4Vectors_0.36.1          BiocGenerics_0.44.0      \n\nloaded via a namespace (and not attached):\n [1] MatrixGenerics_1.8.1        httr_1.4.4                 \n [3] bit64_4.0.5                 jsonlite_1.8.4             \n [5] assertthat_0.2.1            BiocFileCache_2.4.0        \n [7] blob_1.2.3                  GenomeInfoDbData_1.2.8     \n [9] Rsamtools_2.14.0            yaml_2.3.6                 \n[11] progress_1.2.2              pillar_1.8.1               \n[13] RSQLite_2.2.20              lattice_0.20-45            \n[15] glue_1.6.2                  digest_0.6.31              \n[17] XVector_0.38.0              htmltools_0.5.4            \n[19] Matrix_1.5-3                XML_3.99-0.13              \n[21] pkgconfig_2.0.3             biomaRt_2.54.0             \n[23] zlibbioc_1.42.0             BiocParallel_1.30.4        \n[25] tibble_3.1.8                KEGGREST_1.38.0            \n[27] generics_0.1.3              ellipsis_0.3.2             \n[29] cachem_1.0.6                SummarizedExperiment_1.28.0\n[31] lazyeval_0.2.2              cli_3.5.0                  \n[33] magrittr_2.0.3              crayon_1.5.2               \n[35] memoise_2.0.1               evaluate_0.19              \n[37] fansi_1.0.3                 xml2_1.3.3                 \n[39] tools_4.2.1                 prettyunits_1.1.1          \n[41] hms_1.1.2                   BiocIO_1.8.0               \n[43] lifecycle_1.0.3             matrixStats_0.63.0         \n[45] stringr_1.5.0               DelayedArray_0.24.0        \n[47] Biostrings_2.66.0           compiler_4.2.1             \n[49] rlang_1.0.6                 grid_4.2.1                 \n[51] RCurl_1.98-1.9              rjson_0.2.21               \n[53] rappdirs_0.3.3              htmlwidgets_1.5.4          \n[55] bitops_1.0-7                rmarkdown_2.16             \n[57] restfulr_0.0.15             codetools_0.2-18           \n[59] DBI_1.1.3                   curl_4.3.3                 \n[61] R6_2.5.1                    GenomicAlignments_1.34.0   \n[63] knitr_1.41                  rtracklayer_1.58.0         \n[65] fastmap_1.1.0               bit_4.0.5                  \n[67] utf8_1.2.2                  filelock_1.0.2             \n[69] ProtGenerics_1.30.0         stringi_1.7.8              \n[71] parallel_4.2.1              Rcpp_1.0.9                 \n[73] vctrs_0.5.1                 png_0.1-8                  \n[75] dbplyr_2.2.1                tidyselect_1.2.0           \n[77] xfun_0.36                  \n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}