{
  "hash": "af4f51e91832157b48e86419aff6972f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fixed effects family model simulation\"\nauthor: Gibran Hemani\ndate: \"2026-07-20\"\ncategories: []\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n:::\n\n\n\n## Background\n\nWe simulate two populations that differ in:\n\n1. allele frequency at a focal genetic variant; and\n2. mean environment.\n\nMating occurs randomly within population. Each family has two full siblings. The phenotype is generated as\n\n$$\nY_{if} = \\beta_G G_{if} + \\Delta_E Z_f + \\varepsilon_{if},\n$$\n\nwhere $Z_f=1$ denotes population 2, $\\beta_G$ is the direct genetic effect, and $\\Delta_E$ is the population environmental difference.\n\nWe then compare:\n\n$$\nY \\sim G + PC_1\n$$\n\nwith the within-between sibling model\n\n$$\nY_{if} \\sim \\bar G_f\\,b_{\\text{between}}\n+ (G_{if}-\\bar G_f)\\,b_{\\text{within}} + PC_1.\n$$\n\nThe ancestry covariate is simulated as\n\n$$\nPC_{1f}=Z_f+\\eta_f,\\qquad \\eta_f\\sim N(0,\\sigma^2_{PC}).\n$$\n\nThus:\n\n- `pc_sd = 0` gives perfect adjustment for population;\n- larger `pc_sd` gives progressively less effective adjustment;\n- the same PC value is assigned to both siblings.\n\nThis deliberately simplified PC is useful because the amount of residual demographic confounding is under direct control.\n\n## Simulation functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulate_sibling_data <- function(\n    n_families = 5000,\n    prop_pop2 = 0.50,\n    p_pop1 = 0.20,\n    p_pop2 = 0.60,\n    env_pop1 = 0,\n    env_pop2 = 1,\n    beta_g = 1,\n    noise_sd = 1,\n    pc_sd = 0.75,\n    seed = NULL\n) {\n  if (!is.null(seed)) {\n    set.seed(seed)\n  }\n\n  stopifnot(\n    n_families > 1,\n    prop_pop2 > 0, prop_pop2 < 1,\n    p_pop1 > 0, p_pop1 < 1,\n    p_pop2 > 0, p_pop2 < 1,\n    noise_sd >= 0,\n    pc_sd >= 0\n  )\n\n  # Family population membership: 0 = population 1, 1 = population 2.\n  pop2 <- rbinom(n_families, size = 1, prob = prop_pop2)\n  allele_frequency <- ifelse(pop2 == 1, p_pop2, p_pop1)\n\n  # Random mating within population. Parental genotypes are generated under HWE.\n  mother_g <- rbinom(n_families, size = 2, prob = allele_frequency)\n  father_g <- rbinom(n_families, size = 2, prob = allele_frequency)\n\n  # Each sibling independently receives one randomly selected allele\n  # from each parent.\n  maternal_allele <- matrix(\n    rbinom(\n      2 * n_families,\n      size = 1,\n      prob = rep(mother_g / 2, times = 2)\n    ),\n    nrow = n_families,\n    ncol = 2\n  )\n\n  paternal_allele <- matrix(\n    rbinom(\n      2 * n_families,\n      size = 1,\n      prob = rep(father_g / 2, times = 2)\n    ),\n    nrow = n_families,\n    ncol = 2\n  )\n\n  sibling_g <- maternal_allele + paternal_allele\n\n  fam_mean <- rowMeans(sibling_g)\n  centred_g <- sweep(sibling_g, MARGIN = 1, STATS = fam_mean, FUN = \"-\")\n\n  # A family-level imperfect proxy for population structure.\n  pc1_family <- pop2 + rnorm(n_families, mean = 0, sd = pc_sd)\n\n  env_family <- ifelse(pop2 == 1, env_pop2, env_pop1)\n\n  phenotype <- beta_g * sibling_g +\n    matrix(rep(env_family, times = 2), nrow = n_families, ncol = 2) +\n    matrix(\n      rnorm(2 * n_families, mean = 0, sd = noise_sd),\n      nrow = n_families,\n      ncol = 2\n    )\n\n  data.frame(\n    family = rep(seq_len(n_families), times = 2),\n    sibling = rep(1:2, each = n_families),\n    pop2 = rep(pop2, times = 2),\n    pc1 = rep(pc1_family, times = 2),\n    g = as.vector(sibling_g),\n    fam_mean = rep(fam_mean, times = 2),\n    centred_geno = as.vector(centred_g),\n    env = rep(env_family, times = 2),\n    y = as.vector(phenotype)\n  )\n}\n\n\nestimate_models <- function(dat) {\n  population_model <- lm(y ~ g + pc1, data = dat)\n\n  within_between_model <- lm(\n    y ~ fam_mean + centred_geno + pc1,\n    data = dat\n  )\n\n  # Residual genotype variances after adjustment for the same PC.\n  g_resid <- resid(lm(g ~ pc1, data = dat))\n  mean_resid <- resid(lm(fam_mean ~ pc1, data = dat))\n  centred_resid <- resid(lm(centred_geno ~ pc1, data = dat))\n\n  var_g_resid <- var(g_resid)\n  var_mean_resid <- var(mean_resid)\n  var_centred_resid <- var(centred_resid)\n\n  weight_between <- var_mean_resid /\n    (var_mean_resid + var_centred_resid)\n\n  b_pop <- unname(coef(population_model)[\"g\"])\n  b_between <- unname(coef(within_between_model)[\"fam_mean\"])\n  b_within <- unname(coef(within_between_model)[\"centred_geno\"])\n\n  c(\n    b_pop = b_pop,\n    b_between = b_between,\n    b_within = b_within,\n    weight_between = weight_between,\n    reconstructed_pop =\n      weight_between * b_between +\n      (1 - weight_between) * b_within,\n    var_g_resid = var_g_resid,\n    var_mean_resid = var_mean_resid,\n    var_centred_resid = var_centred_resid\n  )\n}\n```\n:::\n\n\n## Theory\n\nWrite population membership as $Z$, with\n\n$$\nP(Z=1)=q.\n$$\n\nThe expected genotype is $2p_1$ in population 1 and $2p_2$ in population 2. Define\n\n$$\nV_Z=q(1-q)\n$$\n\nand\n\n$$\nC_{GZ}=\\operatorname{Cov}(G,Z)\n      =2(p_2-p_1)V_Z.\n$$\n\nThe average genotype variance within populations is\n\n$$\nV_{G,\\text{within pop}}\n=\n(1-q)\\,2p_1(1-p_1)\n+\nq\\,2p_2(1-p_2).\n$$\n\nFor full-sibling pairs,\n\n$$\n\\operatorname{Var}(\\bar G_f\\mid Z)\n=\n\\frac{3}{4}\\operatorname{Var}(G\\mid Z)\n$$\n\nand\n\n$$\n\\operatorname{Var}(G_{if}-\\bar G_f\\mid Z)\n=\n\\frac{1}{4}\\operatorname{Var}(G\\mid Z).\n$$\n\nThe population difference in genotype means contributes only to the between-family component. Therefore,\n\n$$\n\\begin{aligned}\nV_G &=\nV_{G,\\text{within pop}}\n+\n4(p_2-p_1)^2V_Z,\\\\\nV_{\\bar G} &=\n\\frac{3}{4}V_{G,\\text{within pop}}\n+\n4(p_2-p_1)^2V_Z,\\\\\nV_C &=\n\\frac{1}{4}V_{G,\\text{within pop}},\n\\end{aligned}\n$$\n\nwhere $C_{if}=G_{if}-\\bar G_f$.\n\nBecause $PC_1=Z+\\eta$, with\n$\\operatorname{Var}(\\eta)=\\sigma^2_{PC}$,\n\n$$\n\\operatorname{Var}(PC_1)=V_Z+\\sigma^2_{PC}.\n$$\n\nAfter linear adjustment for $PC_1$,\n\n$$\n\\operatorname{Cov}(G,Z\\mid PC_1)\n=\nC_{GZ}\n\\frac{\\sigma^2_{PC}}{V_Z+\\sigma^2_{PC}}.\n$$\n\nThe residual variances are\n\n$$\n\\begin{aligned}\nV_{G\\mid PC}\n&=\nV_G-\\frac{C_{GZ}^2}{V_Z+\\sigma^2_{PC}},\\\\\nV_{\\bar G\\mid PC}\n&=\nV_{\\bar G}-\\frac{C_{GZ}^2}{V_Z+\\sigma^2_{PC}},\\\\\nV_{C\\mid PC}\n&=V_C.\n\\end{aligned}\n$$\n\nIt follows that\n\n$$\nb_{\\text{within}}=\\beta_G,\n$$\n\n$$\nb_{\\text{pop}}\n=\n\\beta_G\n+\n\\Delta_E\n\\frac{\\operatorname{Cov}(G,Z\\mid PC_1)}\n     {V_{G\\mid PC}},\n$$\n\nand\n\n$$\nb_{\\text{between}}\n=\n\\beta_G\n+\n\\Delta_E\n\\frac{\\operatorname{Cov}(G,Z\\mid PC_1)}\n     {V_{\\bar G\\mid PC}}.\n$$\n\nSince $V_{\\bar G\\mid PC}<V_{G\\mid PC}$, positive residual confounding gives\n\n$$\nb_{\\text{between}}>b_{\\text{pop}}>b_{\\text{within}}.\n$$\n\nFinally,\n\n$$\nb_{\\text{pop}}\n=\nw\\,b_{\\text{between}}\n+\n(1-w)b_{\\text{within}},\n$$\n\nwhere\n\n$$\nw=\n\\frac{V_{\\bar G\\mid PC}}\n     {V_{\\bar G\\mid PC}+V_{C\\mid PC}}.\n$$\n\nThe familiar $w=0.75$ applies after population structure has been perfectly removed. With residual population structure, population differences in allele frequency add extra variance to $\\bar G_f$, so $w$ can exceed $0.75$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheoretical_coefficients <- function(\n    prop_pop2 = 0.50,\n    p_pop1 = 0.20,\n    p_pop2 = 0.60,\n    env_pop1 = 0,\n    env_pop2 = 1,\n    beta_g = 1,\n    pc_sd = 0.75\n) {\n  q <- prop_pop2\n  var_z <- q * (1 - q)\n\n  mean_g_pop1 <- 2 * p_pop1\n  mean_g_pop2 <- 2 * p_pop2\n  mean_difference_g <- mean_g_pop2 - mean_g_pop1\n\n  cov_g_z <- mean_difference_g * var_z\n\n  mean_within_pop_var_g <-\n    (1 - q) * 2 * p_pop1 * (1 - p_pop1) +\n    q * 2 * p_pop2 * (1 - p_pop2)\n\n  var_population_means <- mean_difference_g^2 * var_z\n\n  var_g <- mean_within_pop_var_g + var_population_means\n  var_fam_mean <- 0.75 * mean_within_pop_var_g +\n    var_population_means\n  var_centred <- 0.25 * mean_within_pop_var_g\n\n  var_pc <- var_z + pc_sd^2\n\n  cov_g_z_resid <- cov_g_z * pc_sd^2 / var_pc\n\n  var_g_resid <- var_g - cov_g_z^2 / var_pc\n  var_fam_mean_resid <- var_fam_mean - cov_g_z^2 / var_pc\n  var_centred_resid <- var_centred\n\n  env_difference <- env_pop2 - env_pop1\n\n  b_within <- beta_g\n\n  b_pop <- beta_g +\n    env_difference * cov_g_z_resid / var_g_resid\n\n  b_between <- beta_g +\n    env_difference * cov_g_z_resid / var_fam_mean_resid\n\n  weight_between <- var_fam_mean_resid /\n    (var_fam_mean_resid + var_centred_resid)\n\n  c(\n    b_pop = b_pop,\n    b_between = b_between,\n    b_within = b_within,\n    weight_between = weight_between,\n    reconstructed_pop =\n      weight_between * b_between +\n      (1 - weight_between) * b_within,\n    var_g_resid = var_g_resid,\n    var_fam_mean_resid = var_fam_mean_resid,\n    var_centred_resid = var_centred_resid\n  )\n}\n```\n:::\n\n\n## One large simulated sample\n\nWe use:\n\n- causal genetic effect: $\\beta_G=1$;\n- allele frequencies: $p_1=0.20$, $p_2=0.60$;\n- population environmental difference: $\\Delta_E=1$;\n- imperfect PC adjustment: `pc_sd = 0.75`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameters <- list(\n  prop_pop2 = 0.50,\n  p_pop1 = 0.20,\n  p_pop2 = 0.60,\n  env_pop1 = 0,\n  env_pop2 = 1,\n  beta_g = 1,\n  noise_sd = 1,\n  pc_sd = 0.75\n)\n\ndat <- do.call(\n  simulate_sibling_data,\n  c(\n    list(n_families = 100000, seed = 12345),\n    parameters\n  )\n)\n\nest <- estimate_models(dat)\n\ntheory <- do.call(\n  theoretical_coefficients,\n  parameters[names(parameters) != \"noise_sd\"]\n)\n\ncomparison <- data.frame(\n  quantity = c(\n    \"Population coefficient\",\n    \"Between-family coefficient\",\n    \"Within-family coefficient\",\n    \"Between-family variance weight\",\n    \"Weighted reconstruction of population coefficient\"\n  ),\n  theory = unname(theory[c(\n    \"b_pop\",\n    \"b_between\",\n    \"b_within\",\n    \"weight_between\",\n    \"reconstructed_pop\"\n  )]),\n  simulation = unname(est[c(\n    \"b_pop\",\n    \"b_between\",\n    \"b_within\",\n    \"weight_between\",\n    \"reconstructed_pop\"\n  )])\n)\n\nknitr::kable(comparison, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|quantity                                          | theory| simulation|\n|:-------------------------------------------------|------:|----------:|\n|Population coefficient                            | 1.2711|     1.2681|\n|Between-family coefficient                        | 1.3371|     1.3350|\n|Within-family coefficient                         | 1.0000|     0.9940|\n|Between-family variance weight                    | 0.8042|     0.8040|\n|Weighted reconstruction of population coefficient | 1.2711|     1.2681|\n\n\n:::\n:::\n\n\nFor these parameter values, the theoretical values are approximately:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  data.frame(\n    quantity = names(theory),\n    value = unname(theory)\n  ),\n  digits = 4\n)\n```\n\n::: {.cell-output-display}\n\n\n|quantity           |  value|\n|:------------------|------:|\n|b_pop              | 1.2711|\n|b_between          | 1.3371|\n|b_within           | 1.0000|\n|weight_between     | 0.8042|\n|reconstructed_pop  | 1.2711|\n|var_g_resid        | 0.5108|\n|var_fam_mean_resid | 0.4108|\n|var_centred_resid  | 0.1000|\n\n\n:::\n:::\n\n\nThe expected ordering is\n\n$$\nb_{\\text{between}}\\approx 1.337\n>\nb_{\\text{pop}}\\approx 1.271\n>\nb_{\\text{within}}=1.\n$$\n\nThe population coefficient is not equal to the between-family coefficient. It is a residual-variance-weighted average of the between- and within-family coefficients.\n\n## Repeated simulation\n\nA repeated simulation verifies both the coefficient expectations and the weighted identity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_repeated_simulation <- function(\n    n_sim = 200,\n    n_families = 2000,\n    parameters,\n    first_seed = 1000\n) {\n  result <- t(vapply(\n    seq_len(n_sim),\n    FUN = function(i) {\n      dat_i <- do.call(\n        simulate_sibling_data,\n        c(\n          list(\n            n_families = n_families,\n            seed = first_seed + i\n          ),\n          parameters\n        )\n      )\n\n      estimate_models(dat_i)[c(\n        \"b_pop\",\n        \"b_between\",\n        \"b_within\",\n        \"weight_between\",\n        \"reconstructed_pop\"\n      )]\n    },\n    FUN.VALUE = numeric(5)\n  ))\n\n  as.data.frame(result)\n}\n\nsim_results <- run_repeated_simulation(\n  n_sim = 200,\n  n_families = 2000,\n  parameters = parameters\n)\n\nsummary_table <- data.frame(\n  coefficient = c(\n    \"Population\",\n    \"Between family\",\n    \"Within family\"\n  ),\n  theory = unname(theory[c(\n    \"b_pop\",\n    \"b_between\",\n    \"b_within\"\n  )]),\n  simulation_mean = c(\n    mean(sim_results$b_pop),\n    mean(sim_results$b_between),\n    mean(sim_results$b_within)\n  ),\n  simulation_sd = c(\n    sd(sim_results$b_pop),\n    sd(sim_results$b_between),\n    sd(sim_results$b_within)\n  )\n)\n\nsummary_table$mean_minus_theory <-\n  summary_table$simulation_mean - summary_table$theory\n\nknitr::kable(summary_table, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|coefficient    | theory| simulation_mean| simulation_sd| mean_minus_theory|\n|:--------------|------:|---------------:|-------------:|-----------------:|\n|Population     | 1.2711|          1.2700|        0.0245|           -0.0011|\n|Between family | 1.3371|          1.3358|        0.0269|           -0.0013|\n|Within family  | 1.0000|          1.0005|        0.0534|            0.0005|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(\n  sim_results[c(\"b_pop\", \"b_between\", \"b_within\")],\n  names = c(\"Population\", \"Between\", \"Within\"),\n  ylab = \"Estimated genetic coefficient\",\n  main = \"Repeated sibling-pair simulations\"\n)\n\npoints(\n  x = 1:3,\n  y = unname(theory[c(\"b_pop\", \"b_between\", \"b_within\")]),\n  pch = 19\n)\n\nlegend(\n  \"topright\",\n  legend = \"Theoretical value\",\n  pch = 19,\n  bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe reconstruction error should be numerical sampling error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreconstruction_error <-\n  sim_results$b_pop - sim_results$reconstructed_pop\n\nc(\n  mean_error = mean(reconstruction_error),\n  sd_error = sd(reconstruction_error),\n  maximum_absolute_error = max(abs(reconstruction_error))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean_error               sd_error maximum_absolute_error \n          1.689759e-15           3.489602e-14           1.114664e-13 \n```\n\n\n:::\n:::\n\n\nFor balanced sibling pairs and a family-level PC, the equality is essentially exact within each simulated data set because\n\n$$\nG_{if}=\\bar G_f+(G_{if}-\\bar G_f)\n$$\n\nand the two components are orthogonal.\n\n## Effect of PC quality\n\nThe following calculation varies the noise in the ancestry covariate. At `pc_sd = 0`, population is measured perfectly and all three coefficients equal the causal effect. As the PC becomes less informative, residual population confounding increases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npc_grid <- seq(0, 3, length.out = 200)\n\ntheory_by_pc <- t(vapply(\n  pc_grid,\n  FUN = function(pc_value) {\n    theoretical_coefficients(\n      prop_pop2 = parameters$prop_pop2,\n      p_pop1 = parameters$p_pop1,\n      p_pop2 = parameters$p_pop2,\n      env_pop1 = parameters$env_pop1,\n      env_pop2 = parameters$env_pop2,\n      beta_g = parameters$beta_g,\n      pc_sd = pc_value\n    )[c(\"b_pop\", \"b_between\", \"b_within\")]\n  },\n  FUN.VALUE = numeric(3)\n))\n\nmatplot(\n  pc_grid,\n  theory_by_pc,\n  type = \"l\",\n  lty = 1:3,\n  xlab = \"SD of noise in PC1\",\n  ylab = \"Theoretical coefficient\",\n  main = \"Residual confounding as PC quality deteriorates\"\n)\n\nlegend(\n  \"bottomright\",\n  legend = c(\"Population\", \"Between family\", \"Within family\"),\n  lty = 1:3,\n  bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Interpretation\n\nThis simulation isolates a simple case in which the only source of bias is a population environmental difference correlated with allele frequency.\n\nThe results illustrate four points:\n\n1. The within-family coefficient estimates the direct genetic effect because sibling genotype deviations are independent of population-level environment under Mendelian segregation.\n\n2. The between-family coefficient is on the same per-allele scale as the population coefficient because `fam_mean` is a genotype average, not a genotype sum.\n\n3. The between-family coefficient is more strongly affected by between-population confounding than the ordinary population coefficient. Under positive confounding,\n\n   $$\n   b_{\\text{between}}>b_{\\text{pop}}>b_{\\text{within}}.\n   $$\n\n4. The population estimate is the residual-variance-weighted average\n\n   $$\n   b_{\\text{pop}}\n   =\n   w b_{\\text{between}}+\n   (1-w)b_{\\text{within}},\n   $$\n\n   rather than being approximately identical to $b_{\\text{between}}$.\n\nIn real sibling analyses, the difference between the between- and within-family estimates can additionally reflect indirect parental genetic effects, assortative mating, shared family environment, and genotype measurement error. The present simulation intentionally excludes those mechanisms.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.0 (2026-04-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Sequoia 15.2\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/London\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] dplyr_1.2.1\n\nloaded via a namespace (and not attached):\n [1] digest_0.6.39     R6_2.6.1          fastmap_1.2.0     tidyselect_1.2.1 \n [5] xfun_0.57         magrittr_2.0.5    glue_1.8.1        tibble_3.3.1     \n [9] knitr_1.51        pkgconfig_2.0.3   htmltools_0.5.9   generics_0.1.4   \n[13] rmarkdown_2.31    lifecycle_1.0.5   cli_3.6.6         vctrs_0.7.3      \n[17] compiler_4.6.0    tools_4.6.0       pillar_1.11.1     evaluate_1.0.5   \n[21] yaml_2.3.12       otel_0.2.0        rlang_1.2.0       jsonlite_2.0.0   \n[25] htmlwidgets_1.6.4\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}