---
title: "Power of discovery variant to associate with PRS"
author: Gibran Hemani
date: "2025-03-20"
categories: []
---

## Background

Given that a variant associates with a trait due to polygenic confounding, what is the minimum $R^2$ of the PRS required to detect polygenic confounding with 80% power?

```{r}
library(pwr)
library(ggplot2)

param <- expand.grid(
    N = 500000,
    Fdisc = qf(10^-c(8:30), 1, 500000, low=FALSE),
    nsig = c(1, 10, 100)
)

param$r2 = param$Fdisc / param$N
param$validate_alpha = 0.05 / param$nsig
param$validate_r2 = sapply(1:nrow(param), \(i) {
    pwr.r.test(param$N[i], sig.level=param$validate_alpha[i], power=0.8)$r^2
})
param$prs_r2 = param$validate_r2 / param$r2

ggplot(param, aes(x=-log10(pf(Fdisc, 1, 500000, low=F)), y=prs_r2)) +
geom_point(aes(colour=as.factor(nsig))) +
geom_line(aes(colour=as.factor(nsig))) +
theme_bw() +
labs(x="Discovery -log10 p-value", y = "Minimim cor(y,PRS)^2 needed for polygenic confounding to be detected", colour="Number of GWAS\nhits to test")
```




---

```{r}
sessionInfo()
```
